### ISSUE TITLE
API Test Lab's bookstore run.py file will not run for testing

### ISSUE THREAD

**Issue by arvduin** [rsteve-dev/CSC_256_Team8#4]
**Description:**
Attempting to run the Python file run.py within the API Test Lab Bookstore directory in a virtual environment in Terminal results in an error message of "ModuleNotFoundError: No module named 'config'". All requirements were installed into the virtual environment.

**Steps to Reproduce:**
Navigate to the API Test Lab folder -> BOOKSTORE directory within Terminal: 
1. create a virtual environment:
\API Test Lab\bookstore> python -m venv venv 
2. activate the virtual environment:  
    \API Test Lab\bookstore> venv\Scripts\activate
3. install content in requirements . txt file  into the virtual environment(venv)
    \API Test Lab\bookstore> pip install -r requirements.txt
4. Execute :
    \API Test Lab\bookstore> python run.py

**Expected Results:**
(venv) PS C:\Users\xo11o\API Test Lab\bookstore> python run.py
 * Tip: There are .env or .flaskenv files present. Do "pip install python-dotenv" to use them.
 * Serving Flask app 'app'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:3000
Press CTRL+C to quit
 * Restarting with stat
 * Tip: There are .env or .flaskenv files present. Do "pip install python-dotenv" to use them.
 * Debugger is active!
 * Debugger PIN: 124-365-209
 
**Actual Results:**
* Traceback (most recent call last):
File "run.py", line 1 in <module> 
from app import create_app
File "C:\Users\vandu\Documents\GitHub\CSC_256_Team8\API Test Lab\bookstore\app\_\_init__.py", line 3, in <module>
from config import config
* ModuleNotFoundError: No module named 'config'

**Environment:** Windows 11 Pro, Terminal

<img width="806" alt="WindowsTerminal_zyWDIJ37WG" src="https://github.com/rsteve-dev/CSC_256_Team8/assets/145074304/708e3a14-4698-4545-bbf7-30982dc5b452">

**Comment by rsteve-dev** [comment]
Probably the file was ignored while commiting to the remote repository:

1.  Create a file   filename : config.py 
     windows   ** C:\Users\xo11o\API Test Lab\bookstore>type nul > config.py 
      gitbash      **   ~/Desktop/bookstore (main)   $ touch config.py
           
2.  inside config.py  , paste the content below and save:
#__________________________________________

class Config:
    # Basic config settings
    SECRET_KEY = 'your_secret_key'

class DevelopmentConfig(Config):
    DEBUG = True
    # Development-specific settings

class ProductionConfig(Config):
    DEBUG = False
    # Production-specific settings

class TestingConfig(Config):
    TESTING = True
    # Testing-specific settings

config = {
    'development': DevelopmentConfig,
    'production': ProductionConfig,
    'testing': TestingConfig,
    'default': DevelopmentConfig
}

**Comment by arvduin** [comment]
That fixed it, thank you.
